export enum Actions {
    FETCH_AVAILABLE_REGIONS = "FETCH_AVAILABLE_REGIONS",
    FETCH_WEATHER = "FETCH_WEATHER",
    EXPAND_REGION_SELECTOR = "EXPAND_REGION_SELECTOR",
    CHANGE_REGION_SELECTOR_SEARCH_TEXT = "CHANGE_REGION_SELECTOR_SEARCH_TEXT",
    SELECT_REGION = "SELECT_REGION",
    CHANGE_DATE = "CHANGE_DATE",
    CHANGE_DAY_PART = "CHANGE_DAY_PART",
    RESET_REGION_ACTION = "RESET_REGION_ACTION"
}